"""
Vocabulary definitions, weighted keyword lexicons, semantic indicators, and stop words.
No external pre-trained lexical databases are used; all vocabularies are self-contained.
"""

from typing import Dict, List, Set

PROFESSIONAL_KEYWORDS: Dict[str, float] = {

    'meeting': 0.85,
    'meetings': 0.85,
    'project': 0.90,
    'projects': 0.90,
    'deadline': 0.95,
    'deadlines': 0.95,
    'timeline': 0.90,
    'client': 0.90,
    'clients': 0.90,
    'requirement': 0.90,
    'requirements': 0.90,
    'budget': 0.85,
    'budgets': 0.85,
    'schedule': 0.80,
    'scheduled': 0.80,
    'deliverable': 0.90,
    'deliverables': 0.90,
    'milestone': 0.85,
    'milestones': 0.85,
    'sprint': 0.85,
    'sprints': 0.85,
    'backlog': 0.80,
    'task': 0.85,
    'tasks': 0.85,
    'assignment': 0.80,
    'assignments': 0.80,
    'assigned': 0.80,
    'priority': 0.85,
    'priorities': 0.85,
    'prioritize': 0.85,
    'prioritizing': 0.85,
    'roadmap': 0.80,
    'workflow': 0.80,
    'objective': 0.80,
    'objectives': 0.80,
    'scope': 0.80,
    'status': 0.80,
    'progress': 0.85,
    'progressing': 0.85,
    'update': 0.80,
    'updates': 0.80,
    'blocker': 0.85,
    'blockers': 0.85,
    'resource': 0.75,
    'resources': 0.75,
    'overview': 0.75,

    'design': 0.75,
    'development': 0.90,
    'develop': 0.85,
    'developer': 0.80,
    'developers': 0.80,
    'testing': 0.90,
    'test': 0.85,
    'tests': 0.85,
    'tested': 0.85,
    'deployment': 0.90,
    'deploy': 0.85,
    'deployed': 0.85,
    'software': 0.85,
    'hardware': 0.85,
    'prototype': 0.90,
    'integration': 0.90,
    'integrate': 0.85,
    'integrated': 0.85,
    'architecture': 0.90,
    'database': 0.85,
    'server': 0.80,
    'servers': 0.80,
    'api': 0.90,
    'apis': 0.90,
    'pipeline': 0.85,
    'repository': 0.80,
    'module': 0.85,
    'modules': 0.85,
    'interface': 0.80,
    'infrastructure': 0.85,
    'algorithm': 0.85,
    'implementation': 0.90,
    'implement': 0.85,
    'implemented': 0.85,
    'optimization': 0.85,
    'optimize': 0.80,
    'performance': 0.85,
    'security': 0.85,
    'firmware': 0.85,
    'code': 0.80,
    'bug': 0.80,
    'bugs': 0.80,
    'release': 0.85,
    'refactoring': 0.85,
    'refactor': 0.80,
    'sensor': 0.80,
    'microcontroller': 0.85,
    'authentication': 0.90,
    'auth': 0.85,
    'dashboard': 0.85,
    'login': 0.80,
    'logout': 0.80,
    'session': 0.80,
    'sessions': 0.80,
    'expiration': 0.80,
    'expired': 0.75,
    'validation': 0.85,
    'validate': 0.80,
    'validated': 0.80,
    'credentials': 0.80,
    'request': 0.75,
    'requests': 0.75,
    'functional': 0.80,
    'functionality': 0.85,
    'filtering': 0.80,
    'filter': 0.75,
    'backend': 0.85,
    'frontend': 0.85,
    'branch': 0.80,
    'commit': 0.80,
    'push': 0.80,
    'pushed': 0.80,
    'merge': 0.80,
    'component': 0.80,
    'components': 0.80,
    'verification': 0.85,
    'verify': 0.80,
    'verified': 0.80,
    'feature': 0.80,
    'features': 0.80,
    'latency': 0.85,
    'throughput': 0.85,
    'benchmark': 0.85,
    'configuration': 0.80,
    'config': 0.80,
    'technical': 0.85,
    'troubleshooting': 0.85,
    'procedures': 0.80,
    'version': 0.80,
    'setup': 0.75,
    'installation': 0.80,

    'manager': 0.70,
    'engineer': 0.75,
    'engineers': 0.75,
    'architect': 0.80,
    'team': 0.70,
    'stakeholder': 0.85,
    'stakeholders': 0.85,
    'vendor': 0.80,
    'clientele': 0.85,
    'coordinator': 0.75,

    'contract': 0.85,
    'specification': 0.85,
    'specifications': 0.85,
    'documentation': 0.90,
    'docs': 0.85,
    'compliance': 0.85,
    'audit': 0.80,
    'review': 0.80,
    'approval': 0.85,
    'approved': 0.85,
    'research': 0.80,
    'analysis': 0.80,
    'report': 0.80,
    'reports': 0.80,
    'presentation': 0.85,
    'present': 0.75,
    'proposal': 0.85,
    'finance': 0.80,
    'strategy': 0.80,
    'metrics': 0.80,
    'kpi': 0.85,
    'roi': 0.85,
    'conclude': 0.70,
    'concluded': 0.70,
    'conclusion': 0.70,
}

PERSONAL_KEYWORDS: Dict[str, float] = {

    'family': 0.90,
    'wife': 0.90,
    'husband': 0.90,
    'girlfriend': 0.90,
    'boyfriend': 0.90,
    'kids': 0.85,
    'children': 0.85,
    'son': 0.85,
    'daughter': 0.85,
    'mom': 0.85,
    'dad': 0.85,
    'parents': 0.85,
    'sister': 0.85,
    'brother': 0.85,
    'birthday': 0.90,
    'anniversary': 0.90,
    'wedding': 0.90,
    'divorce': 0.90,
    'dating': 0.90,
    'relationship': 0.80,

    'health': 0.85,
    'doctor': 0.85,
    'hospital': 0.85,
    'medicine': 0.80,
    'illness': 0.90,
    'fever': 0.85,
    'headache': 0.80,
    'diet': 0.75,
    'gym': 0.80,
    'workout': 0.75,
    'sick': 0.80,
    'clinic': 0.80,

    'vacation': 0.90,
    'holiday': 0.85,
    'holidays': 0.85,
    'trip': 0.75,
    'flight': 0.70,
    'hotel': 0.70,
    'resort': 0.80,
    'beach': 0.85,
    'movie': 0.85,
    'cinema': 0.85,
    'netflix': 0.90,
    'game': 0.70,
    'party': 0.85,
    'club': 0.70,
    'shopping': 0.80,
    'cooking': 0.75,
    'dinner': 0.65,
    'hobby': 0.80,
    'pet': 0.80,
    'dog': 0.80,
    'cat': 0.80,
    'puppy': 0.80,
    'concert': 0.85,
    'festival': 0.85,
    'gossip': 0.90,
    'cycling': 0.75,
    'football': 0.80,
    'cricket': 0.80,
}

CASUAL_KEYWORDS: Dict[str, float] = {
    'hello': 0.40,
    'hi': 0.35,
    'hey': 0.35,
    'bye': 0.40,
    'goodbye': 0.40,
    'morning': 0.30,
    'evening': 0.30,
    'afternoon': 0.30,
    'weather': 0.65,
    'sunny': 0.60,
    'rain': 0.60,
    'raining': 0.60,
    'traffic': 0.65,
    'coffee': 0.55,
    'tea': 0.50,
    'snack': 0.55,
    'lunch': 0.50,
    'breakfast': 0.50,
    'donuts': 0.55,
    'pizza': 0.55,
    'joke': 0.60,
    'funny': 0.55,
    'laugh': 0.50,
    'laughing': 0.50,
    'weekend': 0.50,
    'awesome': 0.35,
    'cool': 0.35,
    'nice': 0.30,
    'great': 0.25,
    'terrible': 0.30,
    'boring': 0.40,
    'anyway': 0.35,
    'basically': 0.30,
    'whatever': 0.40,
    'stuff': 0.30,
    'crazy': 0.40,
    'haha': 0.50,
}

ACTION_INDICATORS: List[str] = [
    'will handle',
    'will prepare',
    'will verify',
    'will push',
    'will coordinate',
    'will prioritize',
    'will proceed',
    'will provide',
    'will update',
    'will test',
    'will complete',
    'will implement',
    'will review',
    'i will',
    'you can present',
    'can you provide',
    'i can complete',
    'i expect to complete',
    'needs to',
    'need to',
    'should build',
    'should implement',
    'must deliver',
    'assigned to',
    'responsible for',
    'going to work on',
    'working on',
    'take care of',
    'action item',
    'plan to',
    'we will implement',
    'let us build',
    "let's build",
    "let's finish",
    "let's start",
    "let's summarize",
    'need to complete',
    'follow up on',
    'first, complete',
    'second, move',
    'third, complete',
    'fourth, finalize',
    'please include',
    'please make sure',
    'please inform',
    'keep you updated',
]

DECISION_INDICATORS: List[str] = [
    'we decided',
    'decided to',
    'agreed that',
    'we agree',
    'i agree',
    'agreed',
    'approved',
    'that works for me',
    'consensus is',
    'chosen to',
    'selected',
    'finalized',
    'confirmed that',
    'resolved that',
    'concluded that',
    'we will use',
    'we will proceed',
    'the decision is',
    'signed off on',
    'we should verify',
    "let's conclude",
]

DEADLINE_INDICATORS: List[str] = [
    'by friday',
    'by monday',
    'by tomorrow',
    'today',
    'within one working day',
    'due date',
    'deadline is',
    'due on',
    'before end of day',
    'end of week',
    'next sprint',
    'next week',
    'by next month',
    'milestone date',
    'target date',
    'scheduled for',
]

DOMAIN_TOPICS: Set[str] = {
    'authentication', 'dashboard', 'api integration', 'apis', 'database',
    'performance testing', 'documentation', 'frontend', 'backend',
    'architecture', 'deployment', 'testing', 'security', 'session management',
    'presentation', 'sprint planning', 'hardware prototype', 'filter implementation',
    'code review', 'user interface', 'timeline & priorities'
}

STOP_WORDS: Set[str] = {
    'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and',
    'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before',
    'being', 'below', 'between', 'both', 'but', 'by', 'can', 'could', 'did', 'do',
    'does', 'doing', 'down', 'during', 'each', 'few', 'for', 'from', 'further',
    'had', 'has', 'have', 'having', 'he', 'her', 'here', 'hers', 'herself', 'him',
    'himself', 'his', 'how', 'i', 'if', 'in', 'into', 'is', 'isn', "isn't", 'it',
    "it's", 'its', 'itself', 'just', 'me', 'more', 'most', 'my', 'myself', 'no',
    'nor', 'not', 'now', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our',
    'ours', 'ourselves', 'out', 'over', 'own', 'same', 'she', "she's", 'should',
    'so', 'some', 'such', 'than', 'that', "that'll", 'the', 'their', 'theirs',
    'them', 'themselves', 'then', 'there', 'these', 'they', 'this', 'those',
    'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was', 'we', 'were',
    'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will',
    'with', 'won', "won't", 'would', 'you', "you'd", "you'll", "you're", "you've",
    'your', 'yours', 'yourself', 'yourselves'
}
